const users = [
  { id: 1, username: "alice", password: "password123", role: "employee" },
  { id: 2, username: "bob", password: "password123", role: "employee" },
  { id: 3, username: "carol", password: "adminpass", role: "supervisor" },
];

const certificationRequests = [
  {
    id: 1,
    employeeId: 1,
    employeeName: "Alice",
    description: "AWS Certification",
    estimatedBudget: 300,
    expectedDate: "2025-07-01",
    status: "submitted",
  },
  {
    id: 2,
    employeeId: 2,
    employeeName: "Bob",
    description: "Scrum Master Training",
    estimatedBudget: 200,
    expectedDate: "2025-08-10",
    status: "draft",
  },
  {
    id: 3,
    employeeId: 1,
    employeeName: "Alice",
    description: "Advanced React",
    estimatedBudget: 180,
    expectedDate: "2025-09-12",
    status: "approved",
  },
  {
    id: 4,
    employeeId: 2,
    employeeName: "Bob",
    description: "TypeScript Fundamentals",
    estimatedBudget: 220,
    expectedDate: "2025-10-05",
    status: "submitted",
  },
  {
    id: 5,
    employeeId: 1,
    employeeName: "Alice",
    description: "GraphQL Certification",
    estimatedBudget: 275,
    expectedDate: "2025-11-01",
    status: "rejected",
  },
  {
    id: 6,
    employeeId: 2,
    employeeName: "Bob",
    description: "Docker & Kubernetes",
    estimatedBudget: 320,
    expectedDate: "2025-12-15",
    status: "draft",
  },
  {
    id: 7,
    employeeId: 1,
    employeeName: "Alice",
    description: "AI & Machine Learning",
    estimatedBudget: 500,
    expectedDate: "2026-01-20",
    status: "submitted",
  },
  {
    id: 8,
    employeeId: 2,
    employeeName: "Bob",
    description: "DevOps Foundations",
    estimatedBudget: 375,
    expectedDate: "2025-09-20",
    status: "draft",
  },
  {
    id: 9,
    employeeId: 1,
    employeeName: "Alice",
    description: "CI/CD Pipelines",
    estimatedBudget: 210,
    expectedDate: "2025-12-14",
    status: "submitted",
  },
  {
    id: 10,
    employeeId: 1,
    employeeName: "Alice",
    description: "NoSQL Databases",
    estimatedBudget: 385,
    expectedDate: "2025-10-21",
    status: "approved",
  },
  {
    id: 11,
    employeeId: 2,
    employeeName: "Bob",
    description: "Python for Data Science",
    estimatedBudget: 384,
    expectedDate: "2025-12-06",
    status: "draft",
  },
  {
    id: 12,
    employeeId: 2,
    employeeName: "Bob",
    description: "UX/UI Certification",
    estimatedBudget: 410,
    expectedDate: "2025-12-28",
    status: "submitted",
  },
  {
    id: 13,
    employeeId: 2,
    employeeName: "Bob",
    description: "DevOps Foundations",
    estimatedBudget: 210,
    expectedDate: "2025-09-25",
    status: "draft",
  },
  {
    id: 14,
    employeeId: 1,
    employeeName: "Alice",
    description: "JavaScript Best Practices",
    estimatedBudget: 354,
    expectedDate: "2025-11-14",
    status: "rejected",
  },
  {
    id: 15,
    employeeId: 2,
    employeeName: "Bob",
    description: "Python for Data Science",
    estimatedBudget: 428,
    expectedDate: "2025-10-25",
    status: "approved",
  },
  {
    id: 16,
    employeeId: 2,
    employeeName: "Bob",
    description: "REST API Design",
    estimatedBudget: 226,
    expectedDate: "2026-04-09",
    status: "submitted",
  },
  {
    id: 17,
    employeeId: 1,
    employeeName: "Alice",
    description: "Leadership Training",
    estimatedBudget: 277,
    expectedDate: "2025-12-19",
    status: "submitted",
  },
  {
    id: 18,
    employeeId: 2,
    employeeName: "Bob",
    description: "Agile Project Management",
    estimatedBudget: 184,
    expectedDate: "2025-11-13",
    status: "draft",
  },
  {
    id: 19,
    employeeId: 1,
    employeeName: "Alice",
    description: "REST API Design",
    estimatedBudget: 188,
    expectedDate: "2025-08-25",
    status: "rejected",
  },
  {
    id: 20,
    employeeId: 1,
    employeeName: "Alice",
    description: "DevOps Foundations",
    estimatedBudget: 358,
    expectedDate: "2026-02-17",
    status: "draft",
  },
  {
    id: 21,
    employeeId: 2,
    employeeName: "Bob",
    description: "CI/CD Pipelines",
    estimatedBudget: 208,
    expectedDate: "2025-10-07",
    status: "approved",
  },
  {
    id: 22,
    employeeId: 2,
    employeeName: "Bob",
    description: "DevOps Foundations",
    estimatedBudget: 500,
    expectedDate: "2026-02-26",
    status: "approved",
  },
  {
    id: 23,
    employeeId: 2,
    employeeName: "Bob",
    description: "UX/UI Certification",
    estimatedBudget: 296,
    expectedDate: "2026-02-09",
    status: "submitted",
  },
  {
    id: 24,
    employeeId: 2,
    employeeName: "Bob",
    description: "UX/UI Certification",
    estimatedBudget: 358,
    expectedDate: "2026-01-16",
    status: "rejected",
  },
  {
    id: 25,
    employeeId: 2,
    employeeName: "Bob",
    description: "DevOps Foundations",
    estimatedBudget: 154,
    expectedDate: "2025-10-04",
    status: "draft",
  },
  {
    id: 26,
    employeeId: 2,
    employeeName: "Bob",
    description: "REST API Design",
    estimatedBudget: 410,
    expectedDate: "2025-10-27",
    status: "rejected",
  },
  {
    id: 27,
    employeeId: 2,
    employeeName: "Bob",
    description: "Cloud Security",
    estimatedBudget: 430,
    expectedDate: "2025-11-28",
    status: "approved",
  },
  {
    id: 28,
    employeeId: 1,
    employeeName: "Alice",
    description: "Leadership Training",
    estimatedBudget: 163,
    expectedDate: "2026-04-06",
    status: "draft",
  },
  {
    id: 29,
    employeeId: 1,
    employeeName: "Alice",
    description: "NoSQL Databases",
    estimatedBudget: 429,
    expectedDate: "2026-01-01",
    status: "approved",
  },
  {
    id: 30,
    employeeId: 1,
    employeeName: "Alice",
    description: "Cloud Security",
    estimatedBudget: 347,
    expectedDate: "2026-04-04",
    status: "approved",
  },
];

module.exports = { users, certificationRequests };
